import sys

def main():
    if len(sys.argv) < 2:
        print("Uso: python encode.py <archivo_dominio.txt>")
        return

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as f:
            lines = [line.rstrip('\n') for line in f if line.strip()]
    except FileNotFoundError:
        print(f"Error: No se encontró el archivo {input_file}")
        return

    rows = len(lines)
    cols = len(lines[0]) if rows > 0 else 0

    # Listas para almacenar los hechos iniciales y generarlos al final
    initial_facts = []
    
    # ---------------------------------------------------------
    # 1. Generar #program always (Estructura estática)
    # ---------------------------------------------------------
    print("% ======================================")
    print("% GENERATED BY encode.py")
    print("% ======================================")
    print("#program always.\n")
    
    # Dimensiones del mapa [cite: 1]
    print(f"% Celdas {rows}x{cols}: filas 0..{rows-1}, columnas 0..{cols-1}")
    print(f"cell(R,C) :- R = 0..{rows-1}, C = 0..{cols-1}.")
    
    # Direcciones (Son constantes para cualquier mapa) [cite: 3]
    print("\n% Direcciones de movimiento")
    print("dir(u,-1, 0).")
    print("dir(d, 1, 0).")
    print("dir(l, 0,-1).")
    print("dir(r, 0, 1).")

    print("\n% Definiciones estáticas del mapa")
    
    # Recorremos el grid para sacar edificios, estaciones y definiciones de objetos
    for r, line in enumerate(lines):
        for c, char in enumerate(line):
            
            # Edificios (#) [cite: 2]
            if char == '#':
                print(f"building({r},{c}).")
            
            # Estaciones (X) [cite: 2]
            elif char == 'X':
                print(f"station({r},{c}).")
            
            # Taxis (1-9) [cite: 2]
            elif char.isdigit():
                taxi_id = char
                print(f"taxi({taxi_id}).")
                # Guardamos su posición inicial para luego
                initial_facts.append(f"at({taxi_id},{r},{c}).")
            
            # Pasajeros (a-z) [cite: 2]
            elif char.isalpha() and char.islower():
                passenger_id = char
                print(f"passenger({passenger_id}).")
                # Guardamos su posición inicial para luego
                initial_facts.append(f"at({passenger_id},{r},{c}).")

    # ---------------------------------------------------------
    # 2. Generar #program initial (Estado inicial)
    # ---------------------------------------------------------
    print("\n% =========================")
    print("% INITIAL: estado t = 0")
    print("% =========================")
    print("#program initial.\n")
    
    print("% Posiciones iniciales")
    for fact in initial_facts:
        print(fact) # 

if __name__ == "__main__":
    main()